quotes_project/quotes/urls.py
from django.urls import path

from . import views


app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path('by_author/', views.select_by_author, name='select_by_author'),
    path('author/<int:author_id>', views.quotes_by_author, name='quotes_by_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('add_author/', views.add_author, name='add_author'),
    path('about_author/<int:quote_id>', views.about_author, name='about_author'),
    path('tag/<int:tag_id>', views.select_by_tag, name='select_by_tag'),
]

quotes_project/quotes_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
]

quotes_project/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from . import views
from .forms import LoginForm

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes_project/quotes/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=50)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)



class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    

quotes_project/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, Textarea
from .models import Quote, Author



class QuoteForm(ModelForm):
    quote = CharField(min_length=5, max_length=500, required=True, widget=Textarea())

    class Meta:
        model = Quote
        fields = ["quote"]
        exclude = ["tags", "author"]

class AuthorForm(ModelForm):
    fullname = CharField(min_length=5, max_length=50, required=True, widget=Textarea())
    born_date = CharField(min_length=5, max_length=50, required=False, widget=Textarea())
    born_location = CharField(min_length=5, max_length=50, required=False, widget=Textarea())
    description = CharField(min_length=5, max_length=1000, required=False, widget=Textarea())
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']

quotes_project/quotes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Count

from .models import Quote, Tag, Author
from .forms import QuoteForm, AuthorForm


# Create your views here.
def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    top_tags = Tag.objects.annotate(quote_count=Count('quote')).order_by('-quote_count')

    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page, 'paginator': paginator, 'top_tags': top_tags})

def about_author(request, quote_id):
    quote = Quote.objects.get(pk=quote_id)
    author = get_object_or_404(Author, id=quote.author.id)
    return render(request, 'quotes/author_about.html', context={'author': author})

def select_by_tag(request, tag_id):
    tag = Tag.objects.get(pk=tag_id)
    quotes = Quote.objects.filter(tags__id=tag_id).all()
    return render(request, 'quotes/select_by_tag.html', context={'tag': tag, 'quotes': quotes})

def select_by_author(request):
    if request.method == 'POST':
        author_request = request.POST.get('author')
        author = get_object_or_404(Author, id=author_request)
        return redirect('quotes:quotes_by_author', author.id)
    authors = Author.objects.all()
    return render(request, 'quotes/select_by_author.html', context={'authors': authors})

def quotes_by_author(request, author_id):
    author = Author.objects.get(pk=author_id)
    quotes = Quote.objects.filter(author=author.id).all()
    return render(request, 'quotes/quotes_by_author.html', context={'quotes': quotes, 'author': author})

@login_required
def add_quote(request):
    if request.method == 'POST':
        quote_text = request.POST.get('quote_text')
        author_id = request.POST.get('author')
        tag_ids = request.POST.getlist('tags')

        author = get_object_or_404(Author, id=author_id)

        quote = Quote.objects.create(
            quote=quote_text,
            author=author,
        )

        tags = Tag.objects.filter(id__in=tag_ids)
        quote.tags.set(tags)

        return redirect('quotes:root')

    authors = Author.objects.all()
    tags = Tag.objects.all()
    return render(request, 'quotes/add_quote.html', context={'authors': authors, "tags": tags})

@login_required
def add_author(request):
    if request.method == 'POST':
        author_fullname = request.POST.get('author_fullname')
        author_born_date = request.POST.get('author_born_date')
        author_born_location = request.POST.get('author_born_location')
        author_description = request.POST.get('author_description')

        author = Author.objects.create(
                fullname = author_fullname,
                born_date = author_born_date,
                born_location = author_born_location,
                description = author_description
            )
        return redirect('quotes:root')
    return render(request, 'quotes/add_author.html')

quotes_project/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block body %}

<form action="{% url 'quotes:add_author' %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label" for="author_fullname">Author fullname</label>
        <textarea class="form-control" id="author_fullname" name="author_fullname" placeholder="Enter author fullname text"></textarea>
    </div>
    <div class="mb-3">
        <label class="form-label" for="author_born_date">Author born date</label>
        <textarea class="form-control" id="author_born_date" name="author_born_date" placeholder="Enter author dorn date text"></textarea>
    </div>
    <div class="mb-3">
        <label class="form-label" for="author_born_location">Author born location</label>
        <textarea class="form-control" id="author_born_location" name="author_born_location" placeholder="Enter author born location text"></textarea>
    </div>
    <div class="mb-3">
        <label class="form-label" for="author_description">Author description</label>
        <textarea class="form-control" id="author_description" name="author_description" placeholder="Enter author description text"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes_project/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block body %}

<form action="{% url 'quotes:add_quote' %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label" for="author">Author</label>
        <select class="form-select" id="author" name="author">
            {% for author in authors %}
            <option value="{{ author.id }}">{{ author.fullname }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-3">
        <label class="form-label" for="tags">Tags</label>
        <select class="form-select" id="tags" multiple name="tags" size="5">
            {% for tag in tags %}
            <option value="{{ tag.id }}">{{ tag.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-3">
        <label class="form-label" for="quote_text">Quote</label>
        <textarea class="form-control" id="quote_text" name="quote_text" placeholder="Enter quote text"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes_project/quotes/templates/quotes/author_about.html
{% extends 'quotes/base.html'  %}

{% block body %}



<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span class="author-born-location">{{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}} 
    </div>
</div>

{% endblock %}

quotes_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" 
        content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'quotes/style.css' %}">
    <title>Homework</title>
</head>
<body>

<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>
                <a href="{% url 'quotes:select_by_author' %}" class="btn btn-primary">Quotes by author</a>
                {% if user.is_authenticated %}
                <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add quote</a>
                <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add author</a>
                <li>Welcome <b>{{ user.username }}!</b></li>
                <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                {% else %}
                <a href="{% url 'users:signup' %}" class="btn btn-primary">Registration</a>
                <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                {% endif %}
            </p>
        </div>
        
    </div>

    {% block body %}
    {% endblock %}

</div>
    
</body>
</html>

quotes_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block body %}


<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}

        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
            <a href="{% url 'quotes:about_author'  quote.id %}">(about)</a>
            </span>
                <div class="tags">
                    Tags:
                    {% for tag in quote.tags.all %}
                    <a class="tag" href="{% url 'quotes:select_by_tag' tag.id %}">{{tag.name}}</a> 
                    {% endfor %}
                </div>
        </div>

    {%  endfor %}
    <nav>
        <ul class="pagination justify-content-center">
            {% if quotes.has_previous %}
            <li class="page-item">
                <a class="page-link"
                   href="{% url 'quotes:root_paginate' quotes.previous_page_number %}">Previous</a>
            </li>
            {% endif %}

            {% for page_num in paginator.page_range %}
            <li class="page-item {% if page_num == quotes.number %}active{% endif %}">
                <a class="page-link" href="{% url 'quotes:root_paginate' page_num %}">{{ page_num }}</a>
            </li>
            {% endfor %}

            {% if quotes.has_next %}
            <li class="page-item">
                <a class="page-link" href="{% url 'quotes:root_paginate' quotes.next_page_number %}">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    </div>

    <div class="col-md-4 tags-box">
        <h2>Top Tags</h2>
        <ul>
            {% for tag in top_tags %}
            {% if tag.name %}
            <li>
                <span class="tag-item">
                    <a class="tag" style="font-size: 18px" href="{% url 'quotes:select_by_tag' tag.id %}">{{ tag.name }}: {{ tag.quote_count }}</a>
                </span>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
    </div>
    
</div>

{% endblock %}

quotes_project/quotes/templates/quotes/quotes_by_author.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block body %}

<h3>Viewing author: <a href="{% url 'quotes:quotes_by_author' author.id %}">{{author.fullname}}</a></h3>
<div class="row">

    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{author.fullname}}</small>
            <a href="{% url 'quotes:about_author'  quote.id %}">(about)</a>
            </span>
                <div class="tags">
                    Tags:
                    {% for tag in quote.tags.all %}
                    <a class="tag" href="{% url 'quotes:select_by_tag' tag.id %}">{{tag.name}}</a> 
                    {% endfor %}
                </div>
        </div>

    {%  endfor %}
    <nav>
        <ul class="pagination justify-content-center">
            {% if quotes.has_previous %}
            <li class="page-item">
                <a class="page-link"
                   href="{% url 'quotes:root_paginate' quotes.previous_page_number %}">Previous</a>
            </li>
            {% endif %}

            {% for page_num in paginator.page_range %}
            <li class="page-item {% if page_num == quotes.number %}active{% endif %}">
                <a class="page-link" href="{% url 'quotes:root_paginate' page_num %}">{{ page_num }}</a>
            </li>
            {% endfor %}

            {% if quotes.has_next %}
            <li class="page-item">
                <a class="page-link" href="{% url 'quotes:root_paginate' quotes.next_page_number %}">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    </div>

    <div class="col-md-4 tags-box">
        <h2>About author:</h2>
        <ul>
            <h3 class="author-title">{{author.fullname}}</h3>
            <p><strong>Born:</strong> 
                <span class="author-born-date">{{author.born_date}}</span> 
                <span class="author-born-location">{{author.born_location}}</span></p>
            <p><strong>Description:</strong></p>
            <div class="author-description">
                {{author.description}} 
            </div>
        </ul>
    </div>

</div>

{% endblock %}

quotes_project/quotes/templates/quotes/select_by_author.html
{% extends "quotes/base.html" %}

{% block body %}

<form action="{% url 'quotes:select_by_author' %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label" for="author">Author</label>
        <select class="form-select" id="author" name="author">
            {% for author in authors %}
            <option value="{{ author.id }}">{{ author.fullname }}</option>
            {% endfor %}
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset" class="btn btn-secondary">Reset</button>
</form>

{% endblock %}

quotes_project/quotes/templates/quotes/select_by_tag.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block body %}

<h3>Viewing tag: <a href="/tag/{{tag.name}}">{{tag.name}}</a></h3>
<div class="row">

    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
            <a href="{% url 'quotes:about_author'  quote.id %}">(about)</a>
            </span>
                <div class="tags">
                    Tags:
                    {% for tag in quote.tags.all %}
                    <a class="tag" href="{% url 'quotes:select_by_tag' tag.id %}">{{tag.name}}</a> 
                    {% endfor %}
                </div>
        </div>

    {%  endfor %}
    <nav>
        <ul class="pagination justify-content-center">
            {% if quotes.has_previous %}
            <li class="page-item">
                <a class="page-link"
                   href="{% url 'quotes:root_paginate' quotes.previous_page_number %}">Previous</a>
            </li>
            {% endif %}

            {% for page_num in paginator.page_range %}
            <li class="page-item {% if page_num == quotes.number %}active{% endif %}">
                <a class="page-link" href="{% url 'quotes:root_paginate' page_num %}">{{ page_num }}</a>
            </li>
            {% endfor %}

            {% if quotes.has_next %}
            <li class="page-item">
                <a class="page-link" href="{% url 'quotes:root_paginate' quotes.next_page_number %}">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    </div>

</div>

{% endblock %}